name: Test and Deploy

on:
  push:
    branches:
      - master
      - ci

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Tests here

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: '.'
          target: '/home/wbcproject/wbcusa'

      # - name: Executing remote command
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     USERNAME: ${{ secrets.USERNAME }}
      #     PORT: ${{ secrets.PORT }}
      #     KEY: ${{ secrets.SSHKEY }}
      #     script: |
      #       export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
      #       export WORKON_HOME=~/.virtualenvs
      #       export VIRTUALENVWRAPPER_VIRTUALENV=~/.local/bin/virtualenv
      #       source ~/.local/bin/virtualenvwrapper.sh
      #       workon wbcproject
      #       pip3 install -r ./requirements.txt
      #       touch ~/wbcusa/wbcplatform/triggerReload
      #       rm ~/wbcusa/wbcplatform/triggerReload
